name: CI & Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: CI & Deploy Laravel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    #   - name: Setup PHP
    #     uses: shivammathur/setup-php@v2
    #     with:
    #       php-version: '8.3'
    #       extensions: mbstring, pdo, pdo_mysql

    #   - name: Install dependencies
    #     run: |
    #       cp .env.example .env
    #       composer install --no-interaction --prefer-dist --optimize-autoloader
    #       php artisan key:generate

    #   - name: Run only PTest
    #     run: php artisan test tests/Feature

      - name: Set up SSH
        if: success()
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_VP_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        if: success()
        run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_VP_HOST }} "
                cd /var/www/vhosts/reserveo.wpcache.es/httpdocs/reserveo &&
                git pull origin main &&
                /opt/plesk/php/8.3/bin/php artisan config:cache &&
                /opt/plesk/php/8.3/bin/php artisan route:cache
            "