name: CI/CD Reserveo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel to Production via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 217.154.3.82 >> ~/.ssh/known_hosts

      - name: SSH and Pull Latest Code
        run: |
          ssh root@217.154.3.82 "cd ../../var/vhosts/reserveo.wpcache.es/httpdocs/reserveo && git pull origin main"